######################################################################################
###  ██╗░░░░░██╗░██████╗░██╗░░██╗████████╗░██╗░░░░░░░██╗░█████╗░██╗░░░░░███████╗   ###
###  ██║░░░░░██║██╔════╝░██║░░██║╚══██╔══╝░██║░░██╗░░██║██╔══██╗██║░░░░░██╔════╝   ###
###  ██║░░░░░██║██║░░██╗░███████║░░░██║░░░░╚██╗████╗██╔╝██║░░██║██║░░░░░█████╗░░   ###
###  ██║░░░░░██║██║░░╚██╗██╔══██║░░░██║░░░░░████╔═████║░██║░░██║██║░░░░░██╔══╝░░   ###
###  ███████╗██║╚██████╔╝██║░░██║░░░██║░░░░░╚██╔╝░╚██╔╝░╚█████╔╝███████╗██║░░░░░   ###
###  ╚══════╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░╚════╝░╚══════╝╚═╝░░░░░   ###
######################################################################################
# Связь с разработчиком:
# VK - @lightwolf7
# TG - @lightwolf
spit:
  spitDistance: 3.0
  hitTarget: "&a&lПЛЕВОК: &fВ вас плюнул игрок &a%player%"
  hitPlayer: "&a&lПЛЕВОК: &fВы плюнули в игрока &a%target%"